name: dart_amf
version: 2.0.0
description: Provides native Dart access to the AMF protocol and BlazeDS backends
dependencies:
  browser: ">=0.10.0+2 <0.11.0"
  uuid: '>=0.4.1 <0.5.0'
dev_dependencies:
#  unittest: any
author: Glen Blanchard <blanchard.glen@gmail.com>
homepage: https://github.com/blanchg/dart_amf